export default function Page() {
    return(
        <div style={{backgroundColor: "red"}}>
            <h1>Hello! I'm Erin</h1>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis tortor tellus, ac sollicitudin sapien bibendum eu. Ut tincidunt suscipit vehicula. Maecenas non nulla non ex congue dapibus. Quisque nec ante vitae risus sagittis laoreet at eget diam. Sed consectetur tortor suscipit dui malesuada dignissim. Etiam consectetur felis in elit.</p>
            <p>Nulla ac facilisis lorem, suscipit maximus purus. Aenean nec nisi fermentum nibh maximus semper. Duis nec cursus erat, efficitur facilisis sapien. Nullam porta molestie ex sit amet vestibulum. Donec consequat et eros ac posuere. Nulla in laoreet nulla, eget laoreet dolor. Nam ut ipsum consectetur, scelerisque mi ut, pretium odio.</p>

        </div>
    )
}